/**
 * C2 Level Translation Exercises
 * Mastery level translations with highly sophisticated language and abstract concepts
 */

import { CEFRLevel } from '@/lib/models/cefr';
import { TranslationExercise } from './types';

export const C2_TRANSLATION_EXERCISES: TranslationExercise[] = [
  {
    exerciseId: 'tr-c2-001',
    type: 'translation',
    level: CEFRLevel.C2,
    title: 'Literary Criticism',
    englishText: 'The postmodernist deconstruction of narrative coherence fundamentally subverts the epistemological certainties upon which traditional literary analysis was predicated, thereby engendering a profoundly relativistic interpretive framework wherein authorial intent becomes increasingly subordinated to the multiplicitous readings generated by diverse cultural contexts and subjective experiences.',
    correctGermanText: 'Die postmodernistische Dekonstruktion narrativer Kohärenz unterminiert fundamental die epistemologischen Gewissheiten, auf denen die traditionelle Literaturanalyse basierte, wodurch ein zutiefst relativistisches interpretatives Rahmenwerk entsteht, innerhalb dessen die Autorenintention zunehmend den vielfältigen Lesarten untergeordnet wird, die durch diverse kulturelle Kontexte und subjektive Erfahrungen generiert werden.',
    category: 'literary-theory',
    difficulty: 'hard',
    estimatedTime: 60,
    targetGrammar: ['Extended attributes', 'Complex subordination', 'Nominalizations', 'Participle constructions', 'Passive voice'],
    targetVocabulary: ['Dekonstruktion', 'unterminieren', 'epistemologisch', 'Gewissheiten', 'basieren', 'zutiefst', 'unterordnen', 'vielfältig', 'generieren'],
    hints: [
      '"wodurch" for "thereby"',
      'Use extended participial phrase for complex modification',
      'Academic register requires sophisticated vocabulary'
    ],
    completionCount: 0,
    averageScore: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    exerciseId: 'tr-c2-002',
    type: 'translation',
    level: CEFRLevel.C2,
    title: 'Philosophical Phenomenology',
    englishText: 'The phenomenological reduction advocated by Husserl constitutes a methodological bracketing of naturalistic presuppositions, enabling the philosopher to apprehend the essential structures of consciousness itself. This transcendental turn necessitates a rigorous introspective discipline whereby the intentional character of experience is revealed, unveiling the constitutive processes through which meaning emerges in the intersubjective lifeworld.',
    correctGermanText: 'Die von Husserl befürwortete phänomenologische Reduktion konstituiert eine methodologische Einklammerung naturalistischer Voraussetzungen, wodurch es dem Philosophen ermöglicht wird, die wesentlichen Strukturen des Bewusstseins selbst zu erfassen. Diese transzendentale Wende erfordert eine rigorose introspektive Disziplin, wobei der intentionale Charakter der Erfahrung offenbart wird, was die konstitutiven Prozesse enthüllt, durch die Bedeutung in der intersubjektiven Lebenswelt entsteht.',
    category: 'phenomenology',
    difficulty: 'hard',
    estimatedTime: 65,
    targetGrammar: ['Extended participial constructions', 'Genitive chains', 'Passive constructions', 'Relative clauses', 'Nominalization'],
    targetVocabulary: ['befürworten', 'phänomenologisch', 'konstituieren', 'Einklammerung', 'Voraussetzungen', 'erfassen', 'transzendental', 'rigoros', 'intentional', 'konstitutiv', 'intersubjektiv'],
    hints: [
      '"wodurch es ermöglicht wird" for passive enabling',
      'Use "wobei" to introduce simultaneous action',
      'Maintain philosophical precision in terminology'
    ],
    completionCount: 0,
    averageScore: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    exerciseId: 'tr-c2-003',
    type: 'translation',
    level: CEFRLevel.C2,
    title: 'Theoretical Physics',
    englishText: 'The reconciliation of quantum mechanics with general relativity remains the paramount challenge confronting contemporary theoretical physics. The incompatibility between the probabilistic framework underlying quantum phenomena and the deterministic spacetime curvature postulated by Einstein\'s field equations manifests itself most acutely in the seemingly intractable problem of quantum gravity, wherein the attempt to quantize the gravitational field encounters fundamental conceptual and mathematical obstacles.',
    correctGermanText: 'Die Versöhnung der Quantenmechanik mit der allgemeinen Relativitätstheorie bleibt die vorrangige Herausforderung, der sich die zeitgenössische theoretische Physik gegenübersieht. Die Unvereinbarkeit zwischen dem probabilistischen Rahmenwerk, das den Quantenphänomenen zugrunde liegt, und der deterministischen Raumzeitkrümmung, die von Einsteins Feldgleichungen postuliert wird, manifestiert sich am deutlichsten im scheinbar unlösbaren Problem der Quantengravitation, wobei der Versuch, das Gravitationsfeld zu quantisieren, auf fundamentale konzeptuelle und mathematische Hindernisse stößt.',
    category: 'theoretical-physics',
    difficulty: 'hard',
    estimatedTime: 60,
    targetGrammar: ['Extended attributes', 'Relative clauses', 'Participial constructions', 'Genitive constructions', 'Complex subordination'],
    targetVocabulary: ['Versöhnung', 'vorrangig', 'Unvereinbarkeit', 'probabilistisch', 'zugrunde liegen', 'deterministisch', 'Raumzeitkrümmung', 'manifestieren', 'unlösbar', 'quantisieren', 'stoßen auf'],
    hints: [
      '"sich gegenübersehen" for "confront"',
      'Use "wobei" for additional circumstance',
      '"am deutlichsten" for superlative emphasis'
    ],
    completionCount: 0,
    averageScore: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
